import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Categories from '@/components/Categories'
import MainLayout from '@/components/Layout'
import React from 'react'
import Blog from '@/components/Blog'
import { NextPageContext } from 'next'
import { getSession, useSession } from 'next-auth/react'
import dynamic from 'next/dynamic'
import { Session } from 'next-auth'


const inter = Inter({ subsets: ['latin'] })

interface ProfileProps {
  session?: Session;
}

export default function Home(page: React.ReactElement) {

  const { data: session } = useSession();

  console.log(session)

  // odświeżanie sesji
  const reloadSession = () => {
    const event = new Event("visibilitychange")
    document.dispatchEvent(event)
  }

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainLayout>
        {/* <Categories/> */}
        <Blog />
      </MainLayout>
      

    </>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  return {
    props: {
      session,
    }
  }
}
